.TH PWD 1 "September 2026" "mitos-utils 0.1.0" "MITOS User Commands"
.SH NAME
pwd \- print name of current working directory
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
Print the full path of the current working directory.
.SH GLOBAL OPTIONS
Every mitos-utils command additionally accepts \fB\-\-help\fR (print a usage line and exit) and \fB\-\-version\fR. Commands that take file/path arguments also accept \fB\-\-\fR to mark the end of options, so a file literally named e.g. \fB\-oddfile\fR can still be referenced.
.SH EXIT STATUS
0 on success, 1 if the current directory could not be determined.
.SH SEE ALSO
.BR mitos\-box (1),
.BR mitos\-utils\-compat (7),
.BR mitos\-utils\-integration (7)
